### ISSUE TITLE
Please use force_install_dir before logon!

### ISSUE THREAD

**Issue by brayozz** [crazy-max/csgo-server-launcher#114]
Hello,

I was following the tutorial how to manually set the server (the method with listed commands to put), which is available in your installation.md file. When I'm running the `/etc/init.d/csgo-server-launcher create`, as a result I get `Please use force_install_dir before logon! ` and nothing more happens.

**Comment by MayankFawkes** [comment]
Same

**Comment by crazy-max** [comment]
Should be fixed with latest release. Might need to update your `[csgo-server-launcher.conf](https://github.com/crazy-max/csgo-server-launcher/blob/master/csgo-server-launcher.conf)` with following change: https://github.com/crazy-max/csgo-server-launcher/pull/116/files#diff-3bd8107f06bbbd4bf5011da91f90b6ec477658809becb6b2fda12726c85a5935R39
