### ISSUE TITLE
Steam Guard

### ISSUE THREAD

**Issue by aferpa94** [crazy-max/csgo-server-launcher#39]
If you can, add support for steam guard, cause the script freezes when login in while steam asks for the steam guard code. In the mean time I'v disabled steam guard 👍 .

**Comment by crazy-max** [comment]
I put your feature in my backlog thx

**Comment by SdlasHeras** [comment]
+1

**Comment by crazy-max** [comment]
@aferpa94 

Steam guard does not fit with the purpose of a Steam game server. Update and such automated operations can't work with Steam Guard. It also causes technical issues where you cannot actually input the password when steamcmd is started because it waits for input.
So I advise making a dedicated Steam account for your CSGO Server Launcher in order to minimize the risks on your main account. But if your config file is readable by the dedicated user it should be fine. Of course, you shall disable Steam guard on this account for convenience which part of the goal to having a dedicated account for this.
